{{- if .Values.crowdsec.lapi.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer-lapi-key
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    name: crowdsec-bouncer-lapi-key
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: lapi-key
      remoteRef:
        key: CROWDSEC_LAPI_KEY
{{- end }}
