{{- if .Values.garage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage
    app.kubernetes.io/component: object-storage
data:
  garage.toml: |
    metadata_dir = "/var/lib/garage/meta"
    data_dir = "/var/lib/garage/data"
    db_engine = "sqlite"
    replication_factor = 2

    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "10.0.0.1:3901"
    rpc_secret = "__RPC_SECRET__"

    bootstrap_peers = ["10.0.0.4:3901"]

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"

    [admin]
    api_bind_addr = "[::]:3903"
    admin_token = "__ADMIN_TOKEN__"
{{- end }}
