{{- if .Values.minio.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: MINIO_ROOT_USER
    - secretKey: rootPassword
      remoteRef:
        key: MINIO_ROOT_PASSWORD
{{- end }}
