apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-lvm-elitedesk
  namespace: default
  labels:
    app: redis
    protected: "true"
    tier: database
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: openebs-lvmpv
  resources:
    requests:
      storage: 1Gi
