{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "bookmarked.fullname" . }}-externalsecret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bookmarked.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}

  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: SecretStore

  target:
    name: {{ include "bookmarked.fullname" . }}-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "bookmarked.labels" . | nindent 10 }}
      data:
        {{- range .Values.externalSecrets.data }}
        {{ .secretKey }}: {{- printf " \"{{ .%s }}\"" .secretKey }}
        {{- end }}

  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
    {{- end }}
{{- end }}
