apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      targetRevision: v25.10.1
      helm:
        valueFiles:
          - $values/helm-charts/gpu-operator/values-override.yaml
    - repoURL: https://github.com/maxjeffwell/devops-portfolio-manager.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  # Ignore probe fields patched by patch-operator-probes.sh
  # The chart hardcodes operator deployment probes; we patch them post-sync
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: gpu-operator
      jsonPointers:
        - /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
        - /spec/template/spec/containers/0/livenessProbe/periodSeconds
        - /spec/template/spec/containers/0/livenessProbe/failureThreshold
        - /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
        - /spec/template/spec/containers/0/readinessProbe/failureThreshold
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
