apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8up
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://k8up-io.github.io/k8up
      chart: k8up
      targetRevision: 4.10.0
      helm:
        valueFiles:
          - $values/helm-charts/k8up/values-override.yaml
    - repoURL: https://github.com/maxjeffwell/devops-portfolio-manager.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: k8up
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
