apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vertex-platform
  namespace: argocd
  annotations:
    # ArgoCD Image Updater configuration - multiple images
    argocd-image-updater.argoproj.io/image-list: auth=maxjeffwell/vertex-platform-auth-service:latest,analytics=maxjeffwell/vertex-platform-analytics-service:latest
    argocd-image-updater.argoproj.io/auth.update-strategy: digest
    argocd-image-updater.argoproj.io/analytics.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/maxjeffwell/portfolio-orchestration-platform.git
    targetRevision: main
    path: k8s/deployments
    directory:
      include: 'vertex-platform-deployment.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
