apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: channels-dvr
resources:
  - namespace.yaml
  - pv-primary-data.yaml
  - pvc-primary-data.yaml
  - pvc-data.yaml
  - pvc-recordings.yaml
  - networkpolicy.yaml
  - deployment.yaml
  - cronjob-db-sync.yaml
