apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: channels-dvr-primary-data
  namespace: channels-dvr
  labels:
    app: channels-dvr
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: channels-dvr-primary-data
  resources:
    requests:
      storage: 2Ti
