{
 "title": "Caretta Service Map",
 "description": "eBPF service map from Caretta (per-node agents scraped by Alloy into Mimir). Nodes are workloads (Deployment/StatefulSet/DaemonSet/CNPG Cluster...), not pods. 'Hide kinds' defaults to external IPs + node endpoints so the in-cluster traffic is readable; set it to 'none' for everything.",
 "tags": [
  "caretta",
  "network",
  "ebpf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hide_kind",
    "label": "Hide kinds",
    "query": "external|node,external,node,none"
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   {
    "name": "workload",
    "label": "workload",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   { "name": "port", "label": "server port", "query": { "query": "label_values(server_port)" } }
  ]
 },
 "panels": [
  {
   "title": "Service Map ☸️",
   "type": "nodeGraph",
   "gridPos": { "h": 24, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase((sum by (id, title, subTitle, detail__kind, arc__color) (label_replace((label_replace(label_replace(label_replace(label_replace((caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"}), \"detail__kind\", \"$1\", \"server_kind\", \"(.*)\"), \"subTitle\", \"$1\", \"server_namespace\", \"(.*)\"), \"title\", \"$1\", \"server_name\", \"(.*)\"), \"id\", \"$1\", \"server_id\", \"(.*)\") or label_replace(label_replace(label_replace(label_replace((caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"}), \"detail__kind\", \"$1\", \"client_kind\", \"(.*)\"), \"subTitle\", \"$1\", \"client_namespace\", \"(.*)\"), \"title\", \"$1\", \"client_name\", \"(.*)\"), \"id\", \"$1\", \"client_id\", \"(.*)\")  ), \"arc__color\", \"1\", \"link_id\", \"(.*)\")) )[$__range:$__interval])  > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase((sum by (id, source, target, mainStat) ((label_replace(label_replace(label_replace(label_replace((caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"}), \"id\", \"$1\", \"link_id\", \"(.*)\"), \"source\", \"$1\", \"client_id\", \"(.*)\"), \"target\", \"$1\", \"server_id\", \"(.*)\"), \"mainStat\", \"$1\", \"server_port\", \"(.*)\"))) )[$__range:$__interval]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Ports",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (server_port) (increase((caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"})[$__range:$__interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \">\n<div style=\"text-align: center\">\n<p align=\"center\">\n  <img src=\"https://raw.githubusercontent.com/groundcover-com/caretta/main/images/logo.svg\" width=\"75%\" alt=\"caretta\" title=\"caretta\" />\n  <h4>by <a href=\"https://www.groundcover.com\">groundcover</h4>\n\n  \n  [![slack](https://img.shields.io/badge/slack-groundcover-yellowgreen.svg?logo=slack)](http://www.groundcover.com/join-slack)\n  \n</div>\n</p>\n</div>\n</td>\n</table>\n"
   }
  },
  {
   "title": "Top Throughput Workloads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8, sum by (client_name) ((rate(caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"}[$__range:$__interval]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Throughput Connections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7, sum by (client_name, server_name) ( rate( (caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"(node|external)\",} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\", server_kind!~\"(node|external)\"})[$__range:$__interval]) ) )",
     "legendFormat": "{{client_name}} ⮂ {{server_name}}"
    }
   ]
  },
  {
   "title": "Connections (client → server:port, throughput over 5m)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (client_namespace, client_kind, client_name, server_namespace, server_kind, server_name, server_port) (rate((caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"$hide_kind\", server_kind!~\"$hide_kind\"})[5m])) > 0"
    }
   ]
  }
 ]
}