apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - namespace.yaml
  - pv-media-movies.yaml
  - pv-media-tvshows.yaml
  - pvc-media-movies.yaml
  - pvc-media-tvshows.yaml
  - pv-recordings.yaml
  - pvc-recordings.yaml
  - pv-rec-channels.yaml
  - pvc-rec-channels.yaml
  - pv-rec-asustor.yaml
  - pvc-rec-asustor.yaml
  - pvc-config.yaml
  - pvc-cache.yaml
  - middleware-ratelimit.yaml
  - networkpolicy.yaml
  - configmap-encoding.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingressroute-auth.yaml
  - ingressroute-metrics-block.yaml
  - servicemonitor.yaml
