apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-recordings
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ""
  volumeName: jellyfin-recordings
