apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer-external-secret
  namespace: kube-system
spec:
  data:
  - remoteRef:
      key: CROWDSEC_LAPI_KEY
    secretKey: lapi-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: crowdsec-bouncer-lapi-key
