apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-csi-external-secret
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    name: client-info-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        client-info.yml: |
          clients:
          - host: {{ .SYNOLOGY_CSI_HOST }}
            https: false
            password: {{ .SYNOLOGY_CSI_PASSWORD }}
            port: {{ .SYNOLOGY_CSI_PORT }}
            username: {{ .SYNOLOGY_CSI_USERNAME }}
  data:
    - secretKey: SYNOLOGY_CSI_HOST
      remoteRef:
        key: SYNOLOGY_CSI_HOST
    - secretKey: SYNOLOGY_CSI_PASSWORD
      remoteRef:
        key: SYNOLOGY_CSI_PASSWORD
    - secretKey: SYNOLOGY_CSI_PORT
      remoteRef:
        key: SYNOLOGY_CSI_PORT
    - secretKey: SYNOLOGY_CSI_USERNAME
      remoteRef:
        key: SYNOLOGY_CSI_USERNAME
