apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-b2-creds
  namespace: vaultwarden
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: vaultwarden-b2-creds
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: VAULTWARDEN_B2_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: VAULTWARDEN_B2_APP_KEY
