apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-vaultwarden-daily
  namespace: vaultwarden
spec:
  schedule: "0 0 1 * * *"   # 6-field CNPG cron: 01:00 daily
  backupOwnerReference: self
  cluster:
    name: cnpg-vaultwarden
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
