apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- rbac.yaml
- healthchecks-external-secret.yaml
- verifier-cronjob.yaml
configMapGenerator:
- name: healthchecks-code
  files:
  - __init__.py=../../scripts/healthchecks/__init__.py
  - evaluate.py=../../scripts/healthchecks/evaluate.py
  - k8s.py=../../scripts/healthchecks/k8s.py
  - ping.py=../../scripts/healthchecks/ping.py
  - checks.py=../../scripts/healthchecks/checks.py
  - verifier.py=../../scripts/healthchecks/verifier.py
generatorOptions:
  disableNameSuffixHash: true
