apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthchecks-verifier
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healthchecks-verifier
rules:
- apiGroups: ["velero.io"]
  resources: ["backups"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: healthchecks-verifier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: healthchecks-verifier
subjects:
- kind: ServiceAccount
  name: healthchecks-verifier
  namespace: monitoring
