apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firebook-redis-srh-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    name: firebook-redis-srh-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - remoteRef:
        key: FIREBOOK_SRH_TOKEN
      secretKey: SRH_TOKEN
