apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: percona-mongodb
resources:
  - mongodb-educationelly.yaml
  - mongodb-educationelly-graphql.yaml
  - mongodb-intervalai.yaml
