apiVersion: v2
name: gateway
description: GraphQL Gateway - Federated API gateway for portfolio applications
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - graphql
  - gateway
  - api
home: https://github.com/maxjeffwell/portfolio-orchestration-platform
maintainers:
  - name: Jeff Maxwell
    email: jeff@el-jefe.me
dependencies:
  - name: portfolio-common
    version: 1.0.0
    repository: "file://../portfolio-common"
