{{- if .Values.mongodb.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  labels:
    app: mongodb-backup
spec:
  schedule: {{ .Values.mongodb.backup.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: mongodb-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: mongodump
            image: maxjeffwell/mongodb-backup:latest
            command:
            - /bin/bash
            - -c
            - |
              set -e
              TIMESTAMP=$(date +%Y%m%d-%H%M%S)
              BACKUP_FILE="/tmp/intervalai-${TIMESTAMP}.archive"

              echo "Starting MongoDB backup at ${TIMESTAMP}"

              # Run mongodump
              mongodump --uri="${MONGODB_URI}" --archive="${BACKUP_FILE}" --gzip

              echo "Backup complete, uploading to B2..."

              # Upload to Backblaze B2
              aws s3 cp "${BACKUP_FILE}" "s3://${B2_BUCKET}/mongodb-backups/intervalai-${TIMESTAMP}.archive" \
                --endpoint-url="${B2_ENDPOINT}"

              # Clean up local file
              rm -f "${BACKUP_FILE}"

              # List recent backups
              echo "Recent backups in B2:"
              aws s3 ls "s3://${B2_BUCKET}/mongodb-backups/" --endpoint-url="${B2_ENDPOINT}" | tail -5

              echo "Backup uploaded successfully!"
            env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: intervalai-secret
                  key: MONGODB_URI
            - name: B2_BUCKET
              value: {{ .Values.mongodb.backup.b2Bucket | quote }}
            - name: B2_ENDPOINT
              value: {{ .Values.mongodb.backup.b2Endpoint | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.backup.b2SecretName }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.backup.b2SecretName }}
                  key: aws_secret_access_key
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
{{- end }}
