apiVersion: v2
name: monitoring
description: Monitoring stack with Prometheus and Grafana for DevOps Portfolio Manager
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - monitoring
  - prometheus
  - grafana
  - metrics
home: https://github.com/maxjeffwell/devops-portfolio-manager
maintainers:
  - name: Jeff Maxwell
    email: jeff@el-jefe.me
dependencies:
  - name: kube-prometheus-stack
    version: 65.8.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: loki
    version: 6.52.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: alloy
    version: 1.6.0
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled
  - name: mimir-distributed
    version: 6.0.5
    repository: https://grafana.github.io/helm-charts
    condition: mimir-distributed.enabled
