{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}
---
{{- if and .Values.persistence.cache.enabled (not .Values.persistence.cache.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-cache
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.cache.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
{{- end }}
