apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ovms
resources:
  - namespace.yaml
  - ovms-external-secret.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
