apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ovms
resources:
  - namespace.yaml
  - ovms-external-secret.yaml
  - model-pvc.yaml
  - embeddings-config.yaml
  - deployment.yaml
  - embed-m720q.yaml
  - service-embed.yaml
  - service.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
