apiVersion: v1
kind: Namespace
metadata:
  name: ovms
  labels:
    portfolio: "true"
    # 2026-10-07: allows adminAccess ResourceClaims (gpu-claim.yaml).
    resource.kubernetes.io/admin-access: "true"
