apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovms-external-secret
  namespace: ovms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    name: ovms-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - remoteRef: { key: OVMS_S3_ACCESS_KEY }
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef: { key: OVMS_S3_SECRET_KEY }
      secretKey: AWS_SECRET_ACCESS_KEY
