apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ovms-embeddings
  namespace: ovms
  labels:
    portfolio: "true"
spec:
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [ovms-embeddings, ovms-llm] }
  endpoints:
    - port: rest
      path: /metrics
      interval: 60s
