csiDriver:
  name: "org.democratic-csi.nfs-client"

storageClasses:
  - name: asustor-nfs
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: false
    parameters:
      fsType: nfs
    mountOptions:
      - nfsvers=4
      - noatime

driver:
  config:
    driver: nfs-client
    nfs:
      shareHost: 10.0.0.4
      sharePath: "/mnt/k8s-share"
      shareBasePath: "/mnt/k8s-share"
      controllerBasePath: "/mnt/k8s-share"
      dirPermissionsMode: "0777"
      dirPermissionsUser: 0
      dirPermissionsGroup: 0

controller:
  externalResizer:
    enabled: false
  extraVolumes:
    - name: nfs-storage
      nfs:
        server: 10.0.0.4
        path: /mnt/k8s-share
  driver:
    extraVolumeMounts:
      - name: nfs-storage
        mountPath: /mnt/k8s-share

node:
  tolerations: []
