apiVersion: v2
name: firebook
description: FireBook - Bookmark management app with Firebase backend
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - firebook
  - bookmarks
  - firebase
  - react
home: https://github.com/maxjeffwell/bookmarks-capstone-api
maintainers:
  - name: Jeff Maxwell
    email: jeff@el-jefe.me
dependencies:
  - name: portfolio-common
    version: 1.0.0
    repository: "file://../portfolio-common"
