{{- if .Values.mongodb.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup-educationelly-graphql
  labels:
    app: mongodb-backup
spec:
  schedule: {{ .Values.mongodb.backup.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        metadata:
          labels:
            app: mongodb-backup
            portfolio: "true"
        spec:
          restartPolicy: OnFailure
          containers:
          - name: mongodump
            image: maxjeffwell/mongodb-backup:latest
            imagePullPolicy: Always
            command:
            - /bin/bash
            - -c
            - |
              set -e
              TIMESTAMP=$(date +%Y%m%d-%H%M%S)
              BACKUP_FILE="/tmp/educationelly-graphql-${TIMESTAMP}.archive"

              echo "Starting educationelly-graphql MongoDB backup at ${TIMESTAMP}"

              mongodump --uri="${MONGODB_URI}" --archive="${BACKUP_FILE}" --gzip

              echo "Backup complete, uploading to B2..."

              aws s3 cp "${BACKUP_FILE}" "s3://${B2_BUCKET}/mongodb-backups/educationelly-graphql-${TIMESTAMP}.archive" \
                --endpoint-url="${B2_ENDPOINT}"

              rm -f "${BACKUP_FILE}"

              echo "Cleaning up backups older than {{ .Values.mongodb.backup.retentionDays | default 30 }} days..."
              CUTOFF_DATE=$(date -d "-{{ .Values.mongodb.backup.retentionDays | default 30 }} days" +%Y%m%d)
              aws s3 ls "s3://${B2_BUCKET}/mongodb-backups/" --endpoint-url="${B2_ENDPOINT}" | grep educationelly-graphql- | while read -r line; do
                FILE_DATE=$(echo "$line" | awk '{print $NF}' | grep -oP '\d{8}' | head -1)
                FILE_NAME=$(echo "$line" | awk '{print $NF}')
                if [ -n "$FILE_DATE" ] && [ "$FILE_DATE" -lt "$CUTOFF_DATE" ] 2>/dev/null; then
                  echo "Deleting old backup: $FILE_NAME"
                  aws s3 rm "s3://${B2_BUCKET}/mongodb-backups/${FILE_NAME}" --endpoint-url="${B2_ENDPOINT}"
                fi
              done

              echo "Backup uploaded successfully!"
            env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: educationelly-graphql-secret
                  key: MONGODB_URI
            - name: B2_BUCKET
              value: {{ .Values.mongodb.backup.b2Bucket | quote }}
            - name: B2_ENDPOINT
              value: {{ .Values.mongodb.backup.b2Endpoint | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.backup.b2SecretName }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.backup.b2SecretName }}
                  key: aws_secret_access_key
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
{{- end }}
