apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}
  {{- range .Values.auth.databases }}
  {{ .name }}-user: {{ .user | b64enc | quote }}
  {{ .name }}-password: {{ .password | b64enc | quote }}
  {{- end }}
