apiVersion: v1
kind: Secret
metadata:
  name: {{ include "educationelly.fullname" . }}-secret
  labels:
    app: {{ include "educationelly.name" . }}
    chart: {{ include "educationelly.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
